- name: Install python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: setup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup

- name: Install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Start application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemdsetup