- name: install repos
  ansible.builtin.shell: "{{item}}"
  loop:
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

- name: install rabitmq server
  ansible.builtin.yum: 
    name: rabbitmq-server
    state: installed

- name: enable and satrt rabbit mq
  ansible.builtin.service: 
    name: rabbitmq-server
    enabled: true
    state: started

- name: Create rabbit mq
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
