#we need to refer common folder for nodejs file
#Here catalog is one role and common is another role
#we need to import nodejs

- name: install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: setup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup

- name: Install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app
    
- name: Load schema
  ansible.builtin.import_role:
    name: common
    tasks_from: loadschema

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemdsetup
