- name: check if roboshop user exist or not
  ansible.builtin.command: id roboshop
  register: output
  ignore_errors: true

- name: create roboshop user
  when: output.rc == 1
  ansible.builtin.user:
    name: roboshop

- name: check if app directory exists or not
  ansible.builtin.stat:
    path: /app
  register: out

- name: create app directory if it doest not exist
  when: out.stat.exists == false
  ansible.builtin.file:
    path: /app
    state: directory

- name: "download {{component}} artifact"
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp

- name: Extract {{component}}
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes