- name: Copy catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Demon relod
  ansible.builtin.systemd:
    daemon-reload: true